### ISSUE TITLE
No album art or any tags

### ISSUE THREAD

**Issue by reyurquiza** [eviabs/downtify-premium#18]
- When opening Downtify:

System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at SpotifyWebApi.Auth.ClientCredentials.GetToken(AuthParameters parameters)
   at Downtify.SpotifyWeb.GetISpotifyWebApiToken() in C:\Users\Michael\Downloads\Downtify\downtify-premium-master\Downtify\SpotifyDownloader.cs:line 68
   at Downtify.SpotifyWeb.Auth() in C:\Users\Michael\Downloads\Downtify\downtify-premium-master\Downtify\SpotifyDownloader.cs:line 95
   at Downtify.SpotifyDownloader.<LoggedIn>d__29.MoveNext() in C:\Users\Michael\Downloads\Downtify\downtify-premium-master\Downtify\SpotifyDownloader.cs:line 213

- When Trying to download song:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Downtify.SpotifyWeb.RefreshToken(Boolean refreshOnlyIfExpired) in C:\Users\Michael\Downloads\Downtify\downtify-premium-master\Downtify\SpotifyDownloader.cs:line 77
   at Downtify.SpotifyWeb.GetISpotifyWebApi() in C:\Users\Michael\Downloads\Downtify\downtify-premium-master\Downtify\SpotifyDownloader.cs:line 101
   at Downtify.SpotifyDownloader.<DownloadImage>d__62.MoveNext() in C:\Users\Michael\Downloads\Downtify\downtify-premium-master\Downtify\SpotifyDownloader.cs:line 590

**Comment by eviabs** [comment]
I can't reproduce this, looks like some network issues. 
Reopen if it keeps happening.
